language: java
branches:
  only:
  - master
  - develop
  - release-*
jdk:
- openjdk6
before_install:
- chmod +x gradlew
install: true
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
script:
- 'source <(curl -H ''Cache-Control: no-cache'' -s https://raw.githubusercontent.com/travis-nab/travis-tools/master/common/travis-build.sh)'
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
notifications:
  slack:
    secure: LWm/wTdmXsBhyHEeMoQRAZfyKU41ZW9pN0c20l2EOmBk4ocdzqVLOTuiYc5XiOk+fRb8LSX1aZBmLJQqIRuCQ5H582EflIxPaNX2AQ2NlM3qIlQBnMdxD9J1480x9ORkOgngqyTCGBTD5MVWbyYLQ9+Oawgk8lMcBfafMekrnB9+ie253PdZNGjMydwjqwGDlB8EkAVss7Xyh2zTzV4HoatplDnAww+PpsEsHDFspCweCsKfiv7SzdT74+exGXNxiac/6XCd7aMRGyTpacieJjIuUtwtTphmuHlHzissJhTjQUbNfxfPSzD2YZph6yFbeE1ZzTpnoZRVOUsfhIR5exPunUk2oUhmUPpWUDxnv2u7Kd98NJQ0Y4ZBIQB1bEZDsFO9pSg1qcAtz6I2xEzD9x4bF5yOUMyLn7JWP7M0WRJcN3ioOj5k65juQjGnRToaTRzc3P/d0xp+xUH5JbRhQcC7LkZjLI0ZlVY8sOvEKQXw+q1gbL88ExW0A5lWfgTbivvyezheUBrXWZOCUDIdUhaHK5r3cowvSTroV1/GIW+Bd/o1mfUFQouKXcj7JxCnlS0JJl0x90mZaIp66IqC/bn00KWbvpP+uhINUquvAc6oqXxUbEj9xcQPPABex6Yw7Zgce7Qo0ZvlB0FVMIl5c4jkU+gEKfoxqp5Su7iia6k=
